// Imports

import styles from "../page.module.css";
import { useEffect, useState } from "react";
import { Newsletter } from "@/types/database";

// Exports

export default function Generation() {

    const [newsletters, setNewsletters] = useState<Newsletter[]>([]);
    const [newslettersLoaded, setNewslettersLoaded] = useState<boolean>(false);
    const [selectedNewsletterId, setSelectedNewsletterId] = useState<number | null>(null);
    const [generateNewsletterStatus, setGenerateNewsletterStatus] = useState<boolean>(false);
    const [generatedNewsletterHtml, setGeneratedNewsletterHtml] = useState<string | null>(null);
    const [errorMessage, setErrorMessage] = useState<string | null>(null);

    useEffect(() => {
        const getNewsletters = async function () {
            setNewslettersLoaded(false);
            try{

                const response = await fetch('/api/newsletters', {
                    method: 'GET',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                });

                if(!response.ok) {
                    console.error('Failed to fetch newsletters');
                    return;
                }

                const data = await response.json();

                if(data.status) {
                    setNewsletters(data.data);
                } else {
                    console.error(data.message);
                }

            } catch(error: unknown) {
                console.error('Failed to fetch newsletters');
                return;
            } finally {
                setNewslettersLoaded(true);
            }

        }
        getNewsletters();
    }, []);

    const handleGenerateNewsletter = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();

        if(!selectedNewsletterId) {
            setErrorMessage('Please select a newsletter');
            return;
        }

        setGenerateNewsletterStatus(true);
        setErrorMessage(null);

        try{
            
            const response = await fetch('/api/ai', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ newsletterId: selectedNewsletterId }),
            });

            const data = await response.json();

            if(data.status) {
                setGeneratedNewsletterHtml(data.data);
                setErrorMessage(null);
            } else {
                setErrorMessage(data.message || 'Failed to generate newsletter');
            }

        } catch(error: unknown) {
            const errorMsg = error instanceof Error ? error.message : 'Unknown error while generating newsletter';
            setErrorMessage(`Network error: ${errorMsg}`);
        } finally {
            setGenerateNewsletterStatus(false);
        }
    }

    const handleDownloadNewsletter = () => {
        if(!generatedNewsletterHtml) return;

        const fullHtml = `<!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Newsletter</title>
            </head>
            <body>
                ${generatedNewsletterHtml}
            </body>
            </html>
        `;

        const blob = new Blob([fullHtml], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `newsletter-${new Date().getTime()}.html`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }

    const handleResetNewsletter = () => {
        setGeneratedNewsletterHtml(null);
        setSelectedNewsletterId(null);
        setErrorMessage(null);
    }

    if(generatedNewsletterHtml) {
        return (
            <div className={`${styles["column-container"]} ${styles["width-100"]} ${styles["content-start"]} ${styles["align-start"]} ${styles["gap-10"]}`}>
                <div style={{ borderBottom: '1px solid #ccc', padding: '0 0 10px 0' }} className={`${styles["row-container"]} ${styles["width-100"]} ${styles["content-space-between"]} ${styles["align-start"]} ${styles["gap-10"]}`}>
                    <div className={`${styles["column-container"]} ${styles["content-start"]} ${styles["align-start"]} ${styles["gap-5"]}`}>
                        <h1 className={`${styles["title-text"]}`}>AI Generated Newsletter</h1>
                        <p>
                            This newsletter is generated by AI. It is not perfect and may contain errors. 
                            Please review it carefully before sending it to your audience. 
                            If you are not happy with the generated newsletter, you can reset it and try again. 
                            If you are happy with the generated newsletter, you can download it and send it to your audience.
                        </p>
                    </div>
                    <div className={`${styles["row-container"]} ${styles["gap-10"]}`}>
                        <button 
                            className={`${styles["button-structure"]} ${styles["primary-button"]}`} 
                            onClick={handleDownloadNewsletter}
                        >
                            Download
                        </button>
                        <button 
                            className={`${styles["button-structure"]} ${styles["secondary-button"]}`} 
                            onClick={handleResetNewsletter}
                        >
                            Reset
                        </button>
                    </div>
                </div>
                <div className={`${styles["width-100"]}`} dangerouslySetInnerHTML={{ __html: generatedNewsletterHtml }} />
            </div> 
        )
    }

    if(!newslettersLoaded) {
        return (
            <div className={`${styles["column-container"]} ${styles["width-100"]} ${styles["content-start"]} ${styles["align-start"]} ${styles["gap-10"]}`}>
                Loading...
            </div>
        )
    }

    return (
        <div className={`${styles["column-container"]} ${styles["width-100"]} ${styles["content-start"]} ${styles["align-start"]} ${styles["gap-10"]}`}>
            <h1 className={`${styles["title-text"]}`}>AI Generated Newsletters</h1>
            <p>In this section, you can generate newsletters for your brands.</p>
            <form onSubmit={handleGenerateNewsletter} className={`${styles["column-container"]} ${styles["width-100"]} ${styles["content-start"]} ${styles["align-start"]} ${styles["gap-10"]}`}>

                <select 
                    className={`${styles["input-structure"]} ${styles["clickable"]}`} 
                    name="newsletter-generation" 
                    id="newsletter-generation" 
                    value={selectedNewsletterId?.toString() || ''} 
                    onChange={(e) => setSelectedNewsletterId(Number(e.target.value))}
                >
                    <option value="">Select a newsletter</option>
                    {
                        newsletters.map((newsletter: Newsletter) => (
                            <option key={newsletter.id} value={newsletter.id}>{newsletter.name}</option>
                        ))
                    }
                </select>

                <button className={`${styles["button-structure"]} ${styles["primary-button"]}`} type="submit" disabled={generateNewsletterStatus}>Generate Newsletter</button>

            </form>
            {
                errorMessage && (
                    <div 
                        className={`${styles["column-container"]} ${styles["width-100"]} ${styles["content-start"]} ${styles["align-start"]} ${styles["gap-10"]}`}
                        style={{
                            padding: '15px',
                            backgroundColor: '#fee',
                            border: '1px solid #fcc',
                            borderRadius: '8px',
                            color: '#c33'
                        }}
                    >
                        <strong>Error:</strong> {errorMessage}
                    </div>
                )
            }
            {
                generateNewsletterStatus && (
                    <div className={`${styles["column-container"]} ${styles["width-100"]} ${styles["content-start"]} ${styles["align-start"]} ${styles["gap-10"]}`}>
                        Generating newsletter...
                    </div>
                )
            }
        </div>
    )
}