// Imports

import { FormElements } from "@/types/component";

// Exports

export const brandForm: FormElements = {
    title: 'Create Brand',
    description: 'This form is used to create a new brand',
    apiOptionsStatus: false,
    apiOptions: [],
    elements: [
        {
            tag: 'input',
            type: 'text',
            label: 'Name',
            instructions: 'Enter the name of the brand',
            id: 'name',
            name: 'name',
            placeholder: 'e.g. "My Brand"',
            optionApiStatus: false,
            optionApiRef: null,
            options: [],
            required: true,
        },
        {
            tag: 'input',
            type: 'text',
            label: 'Primary Color',
            instructions: 'Enter the primary color of the brand in hex format',
            id: 'primary_color',
            name: 'primary_color',
            placeholder: 'e.g. "#FFFFFF"',
            optionApiStatus: false,
            optionApiRef: null,
            options: [],
            required: true,
        },
        {
            tag: 'input',
            type: 'text',
            label: 'Secondary Color',
            instructions: 'Enter the secondary color of the brand in hex format',
            id: 'secondary_color',
            name: 'secondary_color',
            placeholder: 'e.g. "#FFFFFF"',
            optionApiStatus: false,
            optionApiRef: null,
            options: [],
            required: true,
        },
        {
            tag: 'input',
            type: 'text',
            label: 'Text Color',
            instructions: 'Enter the text color of the brand in hex format',
            id: 'text_color',
            name: 'text_color',
            placeholder: 'e.g. "#000000"',
            optionApiStatus: false,
            optionApiRef: null,
            options: [],
            required: true,
        },
        {
            tag: 'select',
            type: 'text',
            label: 'Text Font',
            instructions: 'Select the text font of the brand',
            id: 'text_font',
            name: 'text_font',
            placeholder: 'e.g. "arial, sans-serif"',
            optionApiStatus: false,
            optionApiRef: null,
            options: [
                {value: 'arial, sans-serif', label: 'Arial'},
                {value: 'verdana, sans-serif', label: 'Verdana'},
                {value: 'georgia, serif', label: 'Georgia'},
                {value: 'times new roman, serif', label: 'Times New Roman'},
                {value: 'courier new, monospace', label: 'Courier New'},
                {value: 'lucida console, monospace', label: 'Lucida Console'},
                {value: 'monaco, monospace', label: 'Monaco'},
                {value: 'consolas, monospace', label: 'Consolas'},
                {value: 'andale mono, monospace', label: 'Andale Mono'},
                {value: 'lucida sans unicode, lucida grande, sans-serif', label: 'Lucida Sans Unicode'},
                {value: 'trebuchet ms, lucida grande, sans-serif', label: 'Trebuchet MS'},
                {value: 'helvetica, arial, sans-serif', label: 'Helvetica'},
                {value: 'tahoma, arial, sans-serif', label: 'Tahoma'},
                {value: 'verdana, arial, sans-serif', label: 'Verdana'},
            ],
            required: true,
        },
    ],
}